# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155382034b81dcdb3adec6941258c5fefb5e6847900400187b27f654d063bfec03eb71554c938aa4a34d5962ea61a2109006075a25717408bd09aa301d8ac6f3

test:
  secret_key_base: e4004211307f7e52dfd793637192d0dbdcbddfaabfbf793b556bee5672672d96b240e785efeb1cfc9ec3b7e9ad92f49257efbaec6ade93f9bb58a5a2bd40ced5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
